# Generated by Django 4.2.6 on 2023-12-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='dono',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='placa',
            field=models.CharField(max_length=20),
        ),
    ]
