# Generated by Django 4.2.6 on 2023-12-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_peca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='marca',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField()),
                ('observacoes', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.peca')),
            ],
        ),
    ]
