# Generated by Django 4.2.6 on 2023-12-04 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_mecanico'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('numero_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cliente')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.mecanico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.servico')),
            ],
        ),
    ]
