# Generated by Django 4.2.6 on 2023-12-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_ordemservico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='data_conclusao',
            new_name='data_saida_prevista',
        ),
    ]
