# Generated by Django 4.2.6 on 2023-12-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_data_conclusao_ordemservico_data_saida_prevista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='data_saida_prevista',
            new_name='data_conclusao',
        ),
    ]
