# Generated by Django 4.2.6 on 2023-12-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_data_saida_prevista_ordemservico_data_conclusao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
    ]
